apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nginx-canary
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/john1436/argocd-nginx-lab.git
    targetRevision: main
    path: canary

  destination:
    server: https://kubernetes.default.svc
    namespace: canary

  syncPolicy:
    automated:
      prune: false
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
