apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-canary
  namespace: canary

spec:
  replicas: 5

  selector:
    matchLabels:
      app: nginx-canary

  template:
    metadata:
      labels:
        app: nginx-canary

    spec:
      containers:
        - name: nginx
          image: nginx:1.29
          ports:
            - containerPort: 80

  strategy:
    canary:
      steps:
        - setWeight: 20

        - pause:
            duration: 30s

        - setWeight: 40

        - pause:
            duration: 30s

        - setWeight: 100
